name: Add Reviewers to Pull Request
on:
  pull_request:
    types:
      - opened

jobs:
  add_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Add all organization members except pull request authors to review
        uses: actions/github-script@v3
        with:
          script: |
            const allMembers = await github.getOrganizationMembers();
            const pullRequestAuthors = await github.getPullRequestReviewers();
            const reviewers = allMembers.filter(member => !pullRequestAuthors.includes(member.login));
            github.addPullRequestReviewers(reviewers);